### ISSUE TITLE
有大佬解决了这个吗？

### ISSUE THREAD

**Issue by wxx0105** [passer-W/VulScanner#5]
error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]

**Comment by wxx0105** [comment]
这样太难装了吧，不懂是不是我python310的问题。。装啥依赖啥报错；mysql数据库说建库，但是命令行报表不存在，那创表有参数吗？我都不知道设什么参数好，或许是我百度和谷歌用的还不够好

**Comment by passer-W** [comment]
下了个python3.10测试了一下（由于该版本python版本较新，有些依赖还未完全支持，我个人不太推荐使用），由于上次打包依赖环境是在很久之前，部分依赖包的版本已经发生较大变动，如psycopg2，目前无法下载2.8.6版本：
`ERROR: No matching distribution found for psycopg2==2.8.6`
故重新整合了一下依赖，已经更新，可以再重新尝试一下。
另外linux、Windows、Mac版本的Django在默认创建表名时存在大小写不一致的问题，以及部分文件的路径寻找错误的问题（正常情况下不影响使用），会在下次更新中一同修正。

**Comment by wxx0105** [comment]
感谢回复，同学建议mysql创库的话最好不要用一体化建站（小皮，直接nvicate），其次就是python3.9.9可以成功部署该扫描器，建议直接开一台虚拟机给该扫描器，再次感谢作者回复！
